// Define actions
export const actionTypes = {
  FETCHING_START: "FETCHING_START",
  FETCHING_SUCCESS: "FETCHING_SUCCESS",
  FETCHING_ERROR: "FETCHING_ERROR",
  SET_IMAGES: 'SET_IMAGES',
  SELECT_IMAGE: 'SELECT_IMAGE',
  DELETE_SELECTED_IMAGES: 'DELETE_SELECTED_IMAGES',
  UPLOAD_IMAGE: 'UPLOAD_IMAGE',
  IS_REFRESH: 'IS_REFRESH'
}